### ISSUE TITLE
Decrypt fails after encrypting more than once

### ISSUE THREAD

**Issue by jayanthkaturi** [degaart/emocrypt#1]
**Steps to reproduce:**

1. Open https://degaart.github.io/emocrypt/
2. Enter password = test, input = test and click encrypt
3. Copy the output and paste it back in input, hit encrypt again
4. Copy the output, paste it back to input, click decrypt
5. Copy the output, paste it back to input, click decrypt. Decrypt fails.

Is this expected?

**Comment by degaart** [comment]
I can reproduce at my end. Looking at it.

**Comment by jayanthkaturi** [comment]
Thanks, good stuff btw. Encryption was never more fun that this.

**Comment by degaart** [comment]
Fixed in the latest commit and the online version. Thanks for the bug report
